### ISSUE TITLE
Developer Story : Developer can create base.html header and footer with (Bootstrap & Django) :

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/Shotokan-Karate#1]
As a User I want  to be presented with a landing  page  so the  I can clearly see header and footer of page in Heroku

## Estimation of Effort :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [x] <label><input type="checkbox" disabled /> 8 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Create boilerplate base.html </label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Create Header of page </label>
- [x] <label><input type="checkbox" disabled /> Task 3 : Create Footer of page</label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Empty page displayed in Heroku </label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Header of page displayed in Heroku </label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Footer of page displayed in Heroku </label>

**Comment by Shaga-Matula** [comment]
Update Estim with checkbox
