### ISSUE TITLE
User Story : Confirmation Messages 

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/Shotokan-Karate#10]
As a Instructor I want  to see messages  so that I can confirm deletion, creation and updates.

## Estimation of Effort :
. 8 Hours

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Add messages imports and code to landing page</label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Identify necessary areas to trigger message </label>
- [x] <label><input type="checkbox" disabled /> Task 3 :  Use bootstrap to generate message format and content</label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Code is producing a message/label>
- [x] <label><input type="checkbox" disabled /> Criteria 2 :  Messages are displaying at correct triggers</label>
- [x] <label><input type="checkbox" disabled /> Criteria 3 :  Messages appearance is bootstrap formatted neat and tidy  </label>

**Comment by Shaga-Matula** [comment]
Add Estom Checkbox
