### ISSUE TITLE
Developer Bug :  No Access to Admin Panel After Creating Custom User

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/Shotokan-Karate#11]
As a "" I want  to ""   so that I ""

## Estimation  Effort (Fibonacci sequence) :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [x] <label><input type="checkbox" disabled /> 8 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Research</label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Test</label>
- [x] <label><input type="checkbox" disabled /> Task 3 : Deploy</label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Access to Admin Panel </label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Access to users  </label>
