### ISSUE TITLE
User Story : Instructor can choose Sensai for each student

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/Shotokan-Karate#12]
As an Instructor  I can assign a  Sensai  so that  the student gets the correct lesson.

## Estimation  Effort (Fibonacci sequence) :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [x] <label><input type="checkbox" disabled /> 8 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [ ] <label><input type="checkbox" disabled /> Task 1 : Create Model for Sensai Table </label>
- [ ] <label><input type="checkbox" disabled /> Task 2 :  Create Classes as necessary </label>
- [ ] <label><input type="checkbox" disabled /> Task 3 :  Render to site</label>

## Acceptance Criteria :
- [ ] <label><input type="checkbox" disabled /> Criteria 1 :  Can Create Sensai </label>
- [ ] <label><input type="checkbox" disabled /> Criteria 2 :  Can view list of Sensai </label>
- [ ] <label><input type="checkbox" disabled /> Criteria 3  :  Can Edit & Delete Sensai</label>
- [ ] <label><input type="checkbox" disabled /> Criteria 4  :  Can do above on Heroku </label>
