### ISSUE TITLE
User Story : Admin Panel

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/Shotokan-Karate#13]
As a Administrator I want to access the admin panel  so that I can create users and kyu levels

## Estimation  Effort (Fibonacci sequence) :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 8 Hour </label>
- [x] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Register Models In Admin Panel</label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Refine fields for Members</label>
- [x] <label><input type="checkbox" disabled /> Task 3 :  Remove all unnecessary registrations</label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Can Create User</label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Can Create Kyu</label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Can Delete Both </label>
