### ISSUE TITLE
User Story : Student Contact Number

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/Shotokan-Karate#14]
As a Instructor I can contact a student by phone so that I can relay details on classes and discuss progression

## Estimation  Effort (Fibonacci sequence) :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [x] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 8 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Create Table in Database</label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Create Field in Student Creation Page</label>
- [x] <label><input type="checkbox" disabled /> Task 3 :  Create Field in Django Admin Panel</label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Criteria 1 :   Contact information displayed in User Creation Page </label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :   Contact Information displayed in Django Admin Panel </label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :   Contact Information Is Displayed in Student View Page  </label>
