### ISSUE TITLE
User Story : Student Can View Sensei Information

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/Shotokan-Karate#15]
As a "" I want  to ""   so that I ""

## Estimation  Effort (Fibonacci sequence) :
- [x] <label><input type="checkbox" disabled /> 1 Hour </label>
- [x] <label><input type="checkbox" disabled /> 2 Hour </label>
- [x] <label><input type="checkbox" disabled /> 3 Hour </label>
- [x] <label><input type="checkbox" disabled /> 5 Hour </label>
- [x] <label><input type="checkbox" disabled /> 8 Hour </label>
- [x] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Add Page To Site</label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Add Details on Instructors</label>
- [x] <label><input type="checkbox" disabled /> Task 3 : Include Link Access to Students</label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Criteria 1 :   Link Displays in Nav Bar</label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :   Student Can Access and View Instructors </label>
