### ISSUE TITLE
User Story : Restrict Access

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/Shotokan-Karate#16]
As an Instructor I want  to have access forbidden 304  on teacher views so that I have a security on my site.

## Estimation  Effort (Fibonacci sequence) :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [x] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 8 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [ ] <label><input type="checkbox" disabled /> Task 1 : Research Restrictions to Views</label>
- [ ] <label><input type="checkbox" disabled /> Task 2 : Implement code on views</label>
- [ ] <label><input type="checkbox" disabled /> Task 3 : Test Access</label>

## Acceptance Criteria :
- [ ] <label><input type="checkbox" disabled /> Criteria 1 :   Teachers can only access Teacher Based Views </label>
- [ ] <label><input type="checkbox" disabled /> Criteria 1 :   Students can only access Student Based Views </label>
- [ ] <label><input type="checkbox" disabled /> Criteria 1 :   Admin can only access Admin Panel </label>
