### ISSUE TITLE
User Story : Instructor can create a student profile (Create)

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/Shotokan-Karate#2]
As a karate instructor, I want to be able to login and create a new student profile, so that I can keep track of their progress. 

## Estimation  Effort (Fibonacci sequence) :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 8 Hour </label>
- [x] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [ ] <label><input type="checkbox" disabled />Task 1 : Design the user interface for creating a new student profile form.</label>
- [ ] <label><input type="checkbox" disabled />Task 2 : Implement the back-end logic to handle the creation of a new student</label> 
- [ ] <label><input type="checkbox" disabled />Task 3 : Validate the input fields to ensure the required information is provided.</label>
- [ ] <label><input type="checkbox" disabled />Task 4 : Save the new student profile to the database.</label>

## Acceptance Criteria :

 - [x] <label><input type="checkbox" disabled />Acceptance Criteria  : The user should be able to enter the student's name, email, phone number, and belt rank.</label>
 - [x] <label><input type="checkbox" disabled />Acceptance Criteria  : The student profile should be saved to the database.</label>
