### ISSUE TITLE
Developer Story : Developer can "Create Database Design"

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/Shotokan-Karate#3]
As a user I want to be able to store club information inside a database  so that retrieve update and delete

## Estimation of Effort :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [x] <label><input type="checkbox" disabled /> 8 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
 
- [x] <label><input type="checkbox" disabled />Task 1 : Write out all of the fields needed in a spread sheet </label>
- [x] <label><input type="checkbox" disabled />Task 2 : Fill in this sheet with spoof user data </label>
- [x] <label><input type="checkbox" disabled />Task 3 : Look for patterns and normalize the data into tables </label>
- [x] <label><input type="checkbox" disabled />Task 4 : Produce a diagram of the Database tables </label>
- [x] <label><input type="checkbox" disabled />Task 5 : Edit Readme.md file with this process </label>

## Acceptance Criteria :

- [x] <label><input type="checkbox" disabled /> Acceptance Criteria " 1 " : Complete Normalization and confer with study material.</label>
- [x] <label><input type="checkbox" disabled />. Acceptance Criteria " 2 " : Verify all patterns and produce Diagram</label>
- [x] <label><input type="checkbox" disabled />. Acceptance Criteria " 3 " : Enter all data into Readme.md file</label>
