### ISSUE TITLE
User Story : Instructor can view an overview of the student (Read)

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/Shotokan-Karate#4]
As a karate instructor, I want to be able to login and view a list of all the students in the dojo, so that I can see an overview of the student population.

## Estimation of Effort :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 8 Hour </label>
- [x] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Design the user interface to display the list of student profiles.  </label>
- [x] <label><input type="checkbox" disabled />  Task 2 : Link the relevant data fields from the database to the form view  </label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> The system should display a list of all student profiles.  </label>
- [x] <label><input type="checkbox" disabled /> Each student profile should display the student's name, email and belt rank.  </label>

**Comment by Shaga-Matula** [comment]
Update est checkbox
