### ISSUE TITLE
User Story : Instructor can Delete a student's profile . (Delete)

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/Shotokan-Karate#5]
As a karate instructor, I want to be able to delete a student's profile, in case they leave the dojo or are no longer active. 

## Estimation of Effort :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 8 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
[ X ] Task 1 : Design the user interface to allow the selection of a student profile for deletion.
[ X ] Task 2 : Implement the back-end logic to delete the selected student profile from the database.
[ X ] Task 3 : Prompt the user for confirmation before deleting the profile.

## Acceptance Criteria :
Acceptance Criteria : The user should be able to select a student profile to delete.
Acceptance Criteria : The system should prompt the user to confirm the deletion.
Acceptance Criteria : The student profile should be removed from the database.

**Comment by Shaga-Matula** [comment]
Update Est with checkboc
