### ISSUE TITLE
User Story : Instructor can update a student's belt rank (Update)

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/Shotokan-Karate#6]
As a karate instructor, I want to be able to update a student's belt rank, so that I can reflect their progress accurately.

## Estimation of Effort :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 8 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Design the user interface to allow the selection of a student profile and the input of a new belt rank</label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Implement the back-end logic to update the student's belt rank in the database </label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled />  The user should be able to select a student profile to update.</label>
- [x] <label><input type="checkbox" disabled /> The user should be able to update the student's belt rank.</label>
- [x] <label><input type="checkbox" disabled /> The updated student profile should be saved to the database.</label>

**Comment by Shaga-Matula** [comment]
Update check box in Est
