### ISSUE TITLE
User Story : Student Login and page

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/Shotokan-Karate#7]
As a Student I want be able to login  so that I can view my own page.

## Estimation of Effort :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [x] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 8 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
 
- [x] <label><input type="checkbox" disabled /> Task 1 : Setup user in groups </label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Apply necessary security </label>
- [x] <label><input type="checkbox" disabled /> Task 3 : Build user site </label>
- [x] <label><input type="checkbox" disabled /> Task 4 : Create code to render page </label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Acceptance Criteria : Security login to different header link prove it works </label>
- [x] <label><input type="checkbox" disabled /> Acceptance Criteria :  Documentation complete </label>
- [x] <label><input type="checkbox" disabled /> Acceptance Criteria : Page rendering as it should </label>
