### ISSUE TITLE
Instructor is able to Upload Images to Cloudinry

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/Shotokan-Karate#8]
As a Instructor I want  to be upload images with kyu edit so that I can change kata images and syllabus listings.

## Estimation of Effort :
. 8 Hours

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Research Cloudinary Documentation</label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Create Django Code for image capture</label>
- [x] <label><input type="checkbox" disabled /> Task 3 :  Create Html and Style </label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Criteria 1 :   Submit Button visable on Kyu Register page</label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :   Upload to Cloudinary confirmed </label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Upload on Heroku to Cloudinary confirmed. </label>
