### ISSUE TITLE
User Story : Edit Kyu Grade 

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/Shotokan-Karate#9]
As a Instructor I want  to edit Kyu grade section  so that I can make changes of images or belt colors according to my DoJo (school).

## Estimation of Effort :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 8 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Write a function or classed based view to edit or delete the kyu form</label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Write a View in Views.py, use previous form. 
- [x] <label><input type="checkbox" disabled /> Task 3 :  Create a HTML\ CSS\Bootstrap page to host the edit or delete</label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Criteria 1 :   Edit or Delete page renders correctly </label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :   Delete Changes show in Database</label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :   Edit Changes Show in Database</label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :   Warning message shows to confirm and commit users choice </label>

**Comment by Shaga-Matula** [comment]
Estom fields check box
